
services:
  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - DATABASE_URL=postgresql://temp_nl1b_user:UMvgg4jCa1ubHMMobWGlmfta94g0wNAf@dpg-crmv49tumphs73fa59p0-a.oregon-postgres.render.com/temp_nl1b
    ports:
      - "8002:8002"
    volumes:
      - ./inventory_management:/inventory_management
    networks:
      - default
  
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - DATABASE_URL=postgresql://temp_nl1b_user:UMvgg4jCa1ubHMMobWGlmfta94g0wNAf@dpg-crmv49tumphs73fa59p0-a.oregon-postgres.render.com/temp_nl1b
    ports:
      - "9001:8001"
    volumes:
      - ./book_catalog:/book_catalog
    networks:
      - default

networks:
  default:
    driver: bridge